gapic_generator_version: 2.40.1
protoc_version: '25.2'
googleapis_commitish: 4795a4575949fcbbb26bd00327540fcd9b1c9de9
libraries_bom_version: 26.38.0
template_excludes:
    - renovate.json
    - .kokoro/build.sh
    - .kokoro/nightly/retry_non_quota.cfg
    - .kokoro/nightly/retry_quota.cfg
    - .kokoro/nightly/samples.cfg
    - .kokoro/presubmit/samples.cfg
    - .kokoro/presubmit/graalvm-native-17.cfg
    - .kokoro/presubmit/graalvm-native.cfg
    - .kokoro/dependencies.sh
    - .github/workflows/approve-readme.yaml
    - .github/workflows/auto-release.yaml
    - .github/workflows/ci.yaml
    - .github/workflows/samples.yaml
    - .kokoro/requirements.in
    - .kokoro/requirements.txt
libraries:
    - api_shortname: "bigquerystorage"
      name_pretty: "BigQuery Storage"
      product_documentation: "https://cloud.google.com/bigquery/docs/reference/storage/"
      client_documentation: "https://cloud.google.com/java/docs/reference/google-cloud-bigquerystorage/latest/history"
      api_description: "is an API for reading data stored in BigQuery. This API provides direct, high-throughput read\naccess to existing BigQuery tables, supports parallel access with automatic liquid sharding, and allows fine-grained\ncontrol over what data is returned."
      issue_tracker: "https://issuetracker.google.com/savedsearches/559654"
      release_level: "stable"
      language: "java"
      repo: "googleapis/java-bigquerystorage"
      repo_short: "java-bigquerystorage"
      distribution_name: "com.google.cloud:google-cloud-bigquerystorage"
      codeowner_team: "@googleapis/api-bigquery"
      api_id: "bigquerystorage.googleapis.com"
      transport: "grpc"
      requires_billing: true
      library_type: "GAPIC_COMBO"
      recommended_package: "com.google.cloud.bigquery.storage.v1"
      GAPICs:
          - proto_path: google/bigquery/storage/v1
          - proto_path: google/bigquery/storage/v1beta1
          - proto_path: google/bigquery/storage/v1beta2
